# Model Architecture (Matches temporal_gcn.py)
model:
  type: "TemporalGCN"
  input_dim: 8              # EMG channels (Myo Armband)
  hidden_dim: 64
  output_dim: 128           # Added to match your code
  dropout: 0.3
  num_layers: 2

# Training (Colab-compatible defaults)
training:
  epochs: 100
  batch_size: 32
  lr: 0.001
  optimizer: "adamw"        # Changed to match your train.py
  weight_decay: 0.0005      # Matches train.py value
  use_cuda: True            # Auto-detects GPU

# Data (EMG-specific)
data:
  sampling_rate: 2000       # Myo Armband default
  window_size: 200          # Samples per window
  stride: 50                # Sliding window step
  graph_type: "functional"  # "functional" or "spatial"
  normalize: True           # Normalize EMG signals

# Evaluation
evaluation:
  frequency: 10             # Epochs between domain metric calculations
  metrics:
    standard: ["accuracy", "f1"]
    domain_adaptation:
      - "h_divergence"
      - "silhouette"
  thresholds:
    h_divergence_warning: 0.5
    silhouette_warning: 0.2
    min_accuracy: 0.7       # For model saving
