# -*- coding: utf-8 -*-
"""params

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgX71IXIlaLUG7F-s7Q5vNtUDWGC7sq-
"""

# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

def get_params():
    paramname = {
        'diversify': [
            ' --latent_domain_num ',
            ' --alpha1 ',
            ' --alpha ',
            ' --lam ',
            ' --use_gnn ',
            ' --gnn_hidden_dim ',
            ' --gnn_output_dim '
        ]
    }

    paramlist = {
        'diversify': [
            [2, 3, 5, 10, 20],          # latent_domain_num
            [0.1, 0.5, 1],              # alpha1
            [0.1, 1, 10],               # alpha
            [0],                        # lam
            [0, 1],                     # use_gnn
            [16, 32, 64],               # gnn_hidden_dim
            [64, 128, 256]              # gnn_output_dim
        ]
    }

    return paramname, paramlist
