# -*- coding: utf-8 -*-
"""monitor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQ60Ar6YejlluG2SZw2hQorL1t6Z8K_1
"""

import matplotlib.pyplot as plt

class TrainingMonitor:
    def __init__(self):
        self.losses = []
        self.accuracies = []

    def update(self, loss, acc):
        self.losses.append(loss)
        self.accuracies.append(acc)

    def plot(self):
        plt.figure(figsize=(12,5))
        plt.subplot(121)
        plt.plot(self.losses)
        plt.title("Training Loss")
        plt.subplot(122)
        plt.plot(self.accuracies)
        plt.title("Accuracy")
        plt.show()